//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSku
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
